### ISSUE TITLE
function to add icons to the results page 

### ISSUE THREAD

**Issue by Suuuuha** [FACN1/easyNaz#132]
like in this pic below
![screenshot from 2017-06-04 16 12 15](https://cloud.githubusercontent.com/assets/24496866/26762037/857303fc-4943-11e7-9b83-44562bc63adc.png)

**Comment by m4v15** [comment]
Audio Recordings, Braille, Big Fonts, Carer, Place for Guide Dog, SMS messaging, Sign Language, Good Lighting,  WheelChair Access, Disabled Parking, Disabled Toilets

**Comment by m4v15** [comment]
see: http://fontawesome.io/accessibility/

**Comment by m4v15** [comment]
especially the bit with the title "If an icon is not an interactive element"

**Comment by m4v15** [comment]
so how I would do it would be to loop through each accessibility option, like we currently do on the serviceInfo.hbs page

**Comment by m4v15** [comment]
but then instead of "<li>{{this}}</li>" we want something more like

<i class="icon class" aria-hidden="true"></i>
<span class="a class which hides this from none screen readers (display:none)">{{this}}</span>

**Comment by m4v15** [comment]
So we need to make a helper that takes one of our accessibilty options and converts it into the correct class to put on an icon, so 

(Wheelchair Access) => "foundicon-wheelchair" 

for example

**Comment by m4v15** [comment]
so then in handlebars it will look like:

<i class= {{helperFunction this}} "aria-hidden="true"></i>

**Comment by AlManarah** [comment]
Note: Be sure that we may need to many icons in the picture not tow or three just.
