### ISSUE TITLE
images for category backgroud

### ISSUE THREAD

**Issue by hibaakel** [FACN1/easyNaz#147]
what you thanks about this images ?
fashion
![fashion](https://user-images.githubusercontent.com/24498230/26870034-4f3915c0-4b77-11e7-90a9-bbbffdf6278e.jpg)
construction
![construction1](https://user-images.githubusercontent.com/24498230/26870055-5c81a9a4-4b77-11e7-8157-0ed511f7e1eb.jpg)

eduction
![education2](https://user-images.githubusercontent.com/24498230/26871273-5385eef6-4b7b-11e7-978d-3410362f5792.jpg)

health
![health](https://user-images.githubusercontent.com/24498230/26870077-698fbb04-4b77-11e7-9867-94af8bf61229.jpg)
tourism
![tourism1](https://user-images.githubusercontent.com/24498230/26870083-6f62bf7c-4b77-11e7-8d79-216f5252d19d.jpg)

sport
![sport2](https://user-images.githubusercontent.com/24498230/26871289-5e7822e8-4b7b-11e7-8b6e-6536cbd43e77.jpg)

IT
![it](https://user-images.githubusercontent.com/24498230/26870170-c723c800-4b77-11e7-8285-9bae6998d47a.jpg)

**Comment by Suuuuha** [comment]
Municipal 
![municipal](https://user-images.githubusercontent.com/24496866/26870236-016aa218-4b78-11e7-81af-739a36f405bd.jpg)

**Comment by m4v15** [comment]
I think they're fine, just make sure the the images are bigger (use advanced setting on google image search and set size to large or something) other wise when they stretch they might look pixelated

**Comment by m4v15** [comment]
Actually I think sport should be a sport, not someone running?

**Comment by m4v15** [comment]
http://www.wallpaperup.com/135891/Architecture_Temple_Greek.html
