### ISSUE TITLE
show love to Esraa ❤️

### ISSUE THREAD

**Issue by Suuuuha** [FACN1/easyNaz#153]
for being a fast QA ..you are GREAT
@hibaakel 
@MohamedOmarii 
@m4v15

**Comment by esraajb** [comment]
hahaha <3 
you guys are doing a great job.

**Comment by Karyum** [comment]
i agree we should buy @esraajb  lots gifts to show him our appreciation here a couple for example:
http://www.japantrendshop.com/super-gorone-desk-use-computer-lying-down-p-2696.html
http://skreened.com/lazzzy/wake-up-for-what-4609204
https://www.amazon.com/CTA-Digital-Pedestal-Stand-Holder/dp/B00AQT653G/?_encoding=UTF8&camp=1789&creative=9325&linkCode=ur2&tag=thehuffingtop-20&linkId=BAJ2E6BUPMJVG4GN
