### ISSUE TITLE
Accessibility types icons

### ISSUE THREAD

**Issue by m4v15** [FACN1/easyNaz#21]
making accessibility types icons (similar to airbnb) for each business

**Comment by AlManarah** [comment]
Great idea,
I think Google can help also
https://www.google.co.il/search?q=accessibility+icons&safe=active&rlz=1C1MSIM_enIL622IL622&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiZ6cOyzfHTAhVB_iwKHS_kCEAQsAQIIw&biw=1280&bih=894

**Comment by m4v15** [comment]
That's great, thanks.
