### ISSUE TITLE
Meeting this week

### ISSUE THREAD

**Issue by m4v15** [FACN1/easyNaz#72]
Hey @AlManarah, 

Hope you are well and that you managed to get the chance to some user testing. 

Would it still be possible to meet with you either tomorrow afternoon or on Tuesday morning, so that you can give us all the feedback and talk through the changes we might make for the MVP?

Thanks

**Comment by AlManarah** [comment]
Thank you for the reminder,
Unfortunately I did not get the chance foe some testing, I hope I will do it with Abbass today.
Yes we can meet I think around 13:00 or later is it good?

**Comment by m4v15** [comment]
Hi Mohammed,

That's great, maybe a bit later would work for us, 14:00?

**Comment by AlManarah** [comment]
OK, See You
